[package]
name = "orion-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
serde_bytes = { workspace = true }
serde_json = { workspace = true }
ulid = { workspace = true }
directories = { workspace = true }
rmp-serde = { workspace = true }
tokio = { version = "1", features = ["io-util"] }

[dev-dependencies]
tokio = { version = "1", features = ["io-util", "rt", "macros"] }
tempfile = { workspace = true }
